# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc-master/Basys-3-Master.xdc

# Block Designs: bd/mblaze_PWM_1000x/mblaze_PWM_1000x.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_PWM_1000x || ORIG_REF_NAME==mblaze_PWM_1000x} -quiet] -quiet

# IP: bd/mblaze_PWM_1000x/ip/mblaze_PWM_1000x_myip_PWM_1000x_0_0/mblaze_PWM_1000x_myip_PWM_1000x_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_PWM_1000x_myip_PWM_1000x_0_0 || ORIG_REF_NAME==mblaze_PWM_1000x_myip_PWM_1000x_0_0} -quiet] -quiet

# IP: bd/mblaze_PWM_1000x/ip/mblaze_PWM_1000x_clk_wiz_0_0/mblaze_PWM_1000x_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_PWM_1000x_clk_wiz_0_0 || ORIG_REF_NAME==mblaze_PWM_1000x_clk_wiz_0_0} -quiet] -quiet

# IP: bd/mblaze_PWM_1000x/ip/mblaze_PWM_1000x_microblaze_0_0/mblaze_PWM_1000x_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_PWM_1000x_microblaze_0_0 || ORIG_REF_NAME==mblaze_PWM_1000x_microblaze_0_0} -quiet] -quiet

# IP: bd/mblaze_PWM_1000x/ip/mblaze_PWM_1000x_dlmb_v10_0/mblaze_PWM_1000x_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_PWM_1000x_dlmb_v10_0 || ORIG_REF_NAME==mblaze_PWM_1000x_dlmb_v10_0} -quiet] -quiet

# IP: bd/mblaze_PWM_1000x/ip/mblaze_PWM_1000x_ilmb_v10_0/mblaze_PWM_1000x_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_PWM_1000x_ilmb_v10_0 || ORIG_REF_NAME==mblaze_PWM_1000x_ilmb_v10_0} -quiet] -quiet

# IP: bd/mblaze_PWM_1000x/ip/mblaze_PWM_1000x_dlmb_bram_if_cntlr_0/mblaze_PWM_1000x_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_PWM_1000x_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mblaze_PWM_1000x_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mblaze_PWM_1000x/ip/mblaze_PWM_1000x_ilmb_bram_if_cntlr_0/mblaze_PWM_1000x_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_PWM_1000x_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mblaze_PWM_1000x_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mblaze_PWM_1000x/ip/mblaze_PWM_1000x_lmb_bram_0/mblaze_PWM_1000x_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_PWM_1000x_lmb_bram_0 || ORIG_REF_NAME==mblaze_PWM_1000x_lmb_bram_0} -quiet] -quiet

# IP: bd/mblaze_PWM_1000x/ip/mblaze_PWM_1000x_mdm_1_0/mblaze_PWM_1000x_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_PWM_1000x_mdm_1_0 || ORIG_REF_NAME==mblaze_PWM_1000x_mdm_1_0} -quiet] -quiet

# IP: bd/mblaze_PWM_1000x/ip/mblaze_PWM_1000x_rst_clk_wiz_0_100M_0/mblaze_PWM_1000x_rst_clk_wiz_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_PWM_1000x_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==mblaze_PWM_1000x_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/mblaze_PWM_1000x/ip/mblaze_PWM_1000x_axi_uartlite_0_0/mblaze_PWM_1000x_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_PWM_1000x_axi_uartlite_0_0 || ORIG_REF_NAME==mblaze_PWM_1000x_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mblaze_PWM_1000x/ip/mblaze_PWM_1000x_xbar_0/mblaze_PWM_1000x_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_PWM_1000x_xbar_0 || ORIG_REF_NAME==mblaze_PWM_1000x_xbar_0} -quiet] -quiet

# IP: bd/mblaze_PWM_1000x/ip/mblaze_PWM_1000x_microblaze_0_axi_periph_0/mblaze_PWM_1000x_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_PWM_1000x_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mblaze_PWM_1000x_microblaze_0_axi_periph_0} -quiet] -quiet

# XDC: bd/mblaze_PWM_1000x/mblaze_PWM_1000x_ooc.xdc
