# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc-master/Basys-3-Master.xdc

# Block Designs: bd/mblaze_I2C/mblaze_I2C.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_I2C || ORIG_REF_NAME==mblaze_I2C} -quiet] -quiet

# IP: bd/mblaze_I2C/ip/mblaze_I2C_clk_wiz_0_0/mblaze_I2C_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_I2C_clk_wiz_0_0 || ORIG_REF_NAME==mblaze_I2C_clk_wiz_0_0} -quiet] -quiet

# IP: bd/mblaze_I2C/ip/mblaze_I2C_microblaze_0_0/mblaze_I2C_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_I2C_microblaze_0_0 || ORIG_REF_NAME==mblaze_I2C_microblaze_0_0} -quiet] -quiet

# IP: bd/mblaze_I2C/ip/mblaze_I2C_dlmb_v10_0/mblaze_I2C_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_I2C_dlmb_v10_0 || ORIG_REF_NAME==mblaze_I2C_dlmb_v10_0} -quiet] -quiet

# IP: bd/mblaze_I2C/ip/mblaze_I2C_ilmb_v10_0/mblaze_I2C_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_I2C_ilmb_v10_0 || ORIG_REF_NAME==mblaze_I2C_ilmb_v10_0} -quiet] -quiet

# IP: bd/mblaze_I2C/ip/mblaze_I2C_dlmb_bram_if_cntlr_0/mblaze_I2C_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_I2C_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mblaze_I2C_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mblaze_I2C/ip/mblaze_I2C_ilmb_bram_if_cntlr_0/mblaze_I2C_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_I2C_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mblaze_I2C_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mblaze_I2C/ip/mblaze_I2C_lmb_bram_0/mblaze_I2C_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_I2C_lmb_bram_0 || ORIG_REF_NAME==mblaze_I2C_lmb_bram_0} -quiet] -quiet

# IP: bd/mblaze_I2C/ip/mblaze_I2C_xbar_0/mblaze_I2C_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_I2C_xbar_0 || ORIG_REF_NAME==mblaze_I2C_xbar_0} -quiet] -quiet

# IP: bd/mblaze_I2C/ip/mblaze_I2C_microblaze_0_axi_periph_0/mblaze_I2C_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_I2C_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mblaze_I2C_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/mblaze_I2C/ip/mblaze_I2C_microblaze_0_axi_intc_0/mblaze_I2C_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_I2C_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mblaze_I2C_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/mblaze_I2C/ip/mblaze_I2C_microblaze_0_xlconcat_0/mblaze_I2C_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_I2C_microblaze_0_xlconcat_0 || ORIG_REF_NAME==mblaze_I2C_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/mblaze_I2C/ip/mblaze_I2C_mdm_1_0/mblaze_I2C_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_I2C_mdm_1_0 || ORIG_REF_NAME==mblaze_I2C_mdm_1_0} -quiet] -quiet

# IP: bd/mblaze_I2C/ip/mblaze_I2C_rst_clk_wiz_0_100M_0/mblaze_I2C_rst_clk_wiz_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_I2C_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==mblaze_I2C_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/mblaze_I2C/ip/mblaze_I2C_axi_gpio_0_0/mblaze_I2C_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_I2C_axi_gpio_0_0 || ORIG_REF_NAME==mblaze_I2C_axi_gpio_0_0} -quiet] -quiet

# IP: bd/mblaze_I2C/ip/mblaze_I2C_axi_uartlite_0_0/mblaze_I2C_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_I2C_axi_uartlite_0_0 || ORIG_REF_NAME==mblaze_I2C_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mblaze_I2C/ip/mblaze_I2C_axi_iic_0_0/mblaze_I2C_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mblaze_I2C_axi_iic_0_0 || ORIG_REF_NAME==mblaze_I2C_axi_iic_0_0} -quiet] -quiet

# XDC: bd/mblaze_I2C/mblaze_I2C_ooc.xdc
