# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.cache/wt [current_project]
set_property parent.project_path F:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_repo_paths {
  f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/ip_repo/myip_DHT11_1.0
  f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/ip_repo/myip_UltraSonic_1.0
  f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/ip_repo/myip_PWM_1000x_1.0
  f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/ip_repo/myip_PWM_1.0
  f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/ip_repo/myip_FND_cntr_1.0
} [current_project]
update_ip_catalog
set_property ip_output_repo f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib F:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_switch_intc/hdl/mblaze_switch_intc_wrapper.v
add_files F:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_switch_intc/mblaze_switch_intc.bd
set_property used_in_implementation false [get_files -all f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_switch_intc/ip/mblaze_switch_intc_clk_wiz_0_0/mblaze_switch_intc_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_switch_intc/ip/mblaze_switch_intc_clk_wiz_0_0/mblaze_switch_intc_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_switch_intc/ip/mblaze_switch_intc_clk_wiz_0_0/mblaze_switch_intc_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_switch_intc/ip/mblaze_switch_intc_microblaze_0_0/mblaze_switch_intc_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_switch_intc/ip/mblaze_switch_intc_microblaze_0_0/mblaze_switch_intc_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_switch_intc/ip/mblaze_switch_intc_microblaze_0_0/mblaze_switch_intc_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_switch_intc/ip/mblaze_switch_intc_dlmb_v10_0/mblaze_switch_intc_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_switch_intc/ip/mblaze_switch_intc_dlmb_v10_0/mblaze_switch_intc_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_switch_intc/ip/mblaze_switch_intc_ilmb_v10_0/mblaze_switch_intc_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_switch_intc/ip/mblaze_switch_intc_ilmb_v10_0/mblaze_switch_intc_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_switch_intc/ip/mblaze_switch_intc_dlmb_bram_if_cntlr_0/mblaze_switch_intc_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_switch_intc/ip/mblaze_switch_intc_ilmb_bram_if_cntlr_0/mblaze_switch_intc_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_switch_intc/ip/mblaze_switch_intc_lmb_bram_0/mblaze_switch_intc_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_switch_intc/ip/mblaze_switch_intc_xbar_0/mblaze_switch_intc_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_switch_intc/ip/mblaze_switch_intc_microblaze_0_axi_intc_0/mblaze_switch_intc_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_switch_intc/ip/mblaze_switch_intc_microblaze_0_axi_intc_0/mblaze_switch_intc_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_switch_intc/ip/mblaze_switch_intc_microblaze_0_axi_intc_0/mblaze_switch_intc_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_switch_intc/ip/mblaze_switch_intc_mdm_1_0/mblaze_switch_intc_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_switch_intc/ip/mblaze_switch_intc_mdm_1_0/mblaze_switch_intc_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_switch_intc/ip/mblaze_switch_intc_rst_clk_wiz_0_100M_0/mblaze_switch_intc_rst_clk_wiz_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_switch_intc/ip/mblaze_switch_intc_rst_clk_wiz_0_100M_0/mblaze_switch_intc_rst_clk_wiz_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_switch_intc/ip/mblaze_switch_intc_rst_clk_wiz_0_100M_0/mblaze_switch_intc_rst_clk_wiz_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_switch_intc/ip/mblaze_switch_intc_axi_gpio_0_0/mblaze_switch_intc_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_switch_intc/ip/mblaze_switch_intc_axi_gpio_0_0/mblaze_switch_intc_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_switch_intc/ip/mblaze_switch_intc_axi_gpio_0_0/mblaze_switch_intc_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_switch_intc/ip/mblaze_switch_intc_axi_uartlite_0_0/mblaze_switch_intc_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_switch_intc/ip/mblaze_switch_intc_axi_uartlite_0_0/mblaze_switch_intc_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_switch_intc/ip/mblaze_switch_intc_axi_uartlite_0_0/mblaze_switch_intc_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all F:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_switch_intc/mblaze_switch_intc_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_switch_intc/ip/mblaze_switch_intc_microblaze_0_0/data/mb_bootloop_le.elf]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/constrs_1/imports/digilent-xdc-master/Basys-3-Master.xdc
set_property used_in_implementation false [get_files F:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/constrs_1/imports/digilent-xdc-master/Basys-3-Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top mblaze_switch_intc_wrapper -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mblaze_switch_intc_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file mblaze_switch_intc_wrapper_utilization_synth.rpt -pb mblaze_switch_intc_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
