@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Nov 23 13:57:02 +0900 2023
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim tb_FND_IP_behav -key {Behavioral:sim_1:Functional:tb_FND_IP} -tclbatch tb_FND_IP.tcl -protoinst "protoinst_files/FND_IP_test.protoinst" -protoinst "protoinst_files/mblaze_DHT11.protoinst" -protoinst "protoinst_files/mblaze_UltraSonic.protoinst" -protoinst "protoinst_files/mblaze_PWM_1000x.protoinst" -protoinst "protoinst_files/mblaze_PWM.protoinst" -protoinst "protoinst_files/mblaze_led.protoinst" -protoinst "protoinst_files/Microblaze_hello.protoinst" -log simulate.log"
call xsim  tb_FND_IP_behav -key {Behavioral:sim_1:Functional:tb_FND_IP} -tclbatch tb_FND_IP.tcl -protoinst "protoinst_files/FND_IP_test.protoinst" -protoinst "protoinst_files/mblaze_DHT11.protoinst" -protoinst "protoinst_files/mblaze_UltraSonic.protoinst" -protoinst "protoinst_files/mblaze_PWM_1000x.protoinst" -protoinst "protoinst_files/mblaze_PWM.protoinst" -protoinst "protoinst_files/mblaze_led.protoinst" -protoinst "protoinst_files/Microblaze_hello.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
