# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z007sclg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/cora_cpu_2019/cora_cpu_2019.cache/wt [current_project]
set_property parent.project_path F:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/cora_cpu_2019/cora_cpu_2019.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:cora-z7-07s:part0:1.1 [current_project]
set_property ip_output_repo f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/cora_cpu_2019/cora_cpu_2019.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files F:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/cora_cpu_2019/cora_cpu_2019.srcs/sources_1/calculator.coe
read_verilog -library xil_defaultlib {
  F:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/cora_cpu_2019/cora_cpu_2019.srcs/sources_1/new/acc.v
  F:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/cora_cpu_2019/cora_cpu_2019.srcs/sources_1/new/alu.v
  F:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/cora_cpu_2019/cora_cpu_2019.srcs/sources_1/new/control_block.v
  F:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/cora_cpu_2019/cora_cpu_2019.srcs/sources_1/imports/new/exam01_combinational_Logic.v
  F:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/cora_cpu_2019/cora_cpu_2019.srcs/sources_1/imports/new/exam02_sequential_logic.v
  F:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/cora_cpu_2019/cora_cpu_2019.srcs/sources_1/new/key_pad_cntr.v
  F:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/cora_cpu_2019/cora_cpu_2019.srcs/sources_1/new/processor.v
  F:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/cora_cpu_2019/cora_cpu_2019.srcs/sources_1/new/program_address_counter.v
  F:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/cora_cpu_2019/cora_cpu_2019.srcs/sources_1/new/Calculator_Top.v
}
read_ip -quiet F:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/cora_cpu_2019/cora_cpu_2019.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci
set_property used_in_implementation false [get_files -all f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/cora_cpu_2019/cora_cpu_2019.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/cora_cpu_2019/cora_cpu_2019.srcs/constrs_1/imports/digilent-xdc-master/Cora-Z7-07S-Master.xdc
set_property used_in_implementation false [get_files F:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/cora_cpu_2019/cora_cpu_2019.srcs/constrs_1/imports/digilent-xdc-master/Cora-Z7-07S-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Calculator_Top -part xc7z007sclg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Calculator_Top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Calculator_Top_utilization_synth.rpt -pb Calculator_Top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
