#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : mblaze_Multifunction_Fan.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Tue Nov 28 15:37:50 +0900 2023
# SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved. 
#
# usage: mblaze_Multifunction_Fan.sh [-help]
# usage: mblaze_Multifunction_Fan.sh [-lib_map_path]
# usage: mblaze_Multifunction_Fan.sh [-noclean_files]
# usage: mblaze_Multifunction_Fan.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'mblaze_Multifunction_Fan.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm xil_defaultlib microblaze_v11_0_2 lmb_v10_v3_0_10 lmb_bram_if_cntlr_v4_0_17 blk_mem_gen_v8_4_4 axi_lite_ipif_v3_0_4 mdm_v3_2_17 lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 interrupt_control_v3_1_4 axi_gpio_v2_0_22 generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_20 fifo_generator_v13_2_5 axi_data_fifo_v2_1_19 axi_crossbar_v2_1_21 lib_pkg_v1_0_2 lib_srl_fifo_v1_0_2 axi_uartlite_v2_0_24)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "mblaze_Multifunction_Fan.sh - Script generated by export_simulation (Vivado v2019.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/4fba" +incdir+"$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/ec67/hdl" +incdir+"F:/Vivado/2019.2/data/xilinx_vip/include" \
    "F:/Vivado/2019.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "F:/Vivado/2019.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "F:/Vivado/2019.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "F:/Vivado/2019.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "F:/Vivado/2019.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "F:/Vivado/2019.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "F:/Vivado/2019.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "F:/Vivado/2019.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "F:/Vivado/2019.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/4fba" +incdir+"$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/ec67/hdl" +incdir+"F:/Vivado/2019.2/data/xilinx_vip/include" \
    "F:/Vivado/2019.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "F:/Vivado/2019.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "F:/Vivado/2019.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/4fba" +incdir+"$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/ec67/hdl" +incdir+"F:/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/mblaze_Multifunction_Fan/ip/mblaze_Multifunction_Fan_clk_wiz_0_1/mblaze_Multifunction_Fan_clk_wiz_0_1_clk_wiz.v" \
    "$ref_dir/../../../bd/mblaze_Multifunction_Fan/ip/mblaze_Multifunction_Fan_clk_wiz_0_1/mblaze_Multifunction_Fan_clk_wiz_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work microblaze_v11_0_2 $vhdlan_opts \
    "$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/f871/hdl/microblaze_v11_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/mblaze_Multifunction_Fan/ip/mblaze_Multifunction_Fan_microblaze_0_1/sim/mblaze_Multifunction_Fan_microblaze_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lmb_v10_v3_0_10 $vhdlan_opts \
    "$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/2e88/hdl/lmb_v10_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/mblaze_Multifunction_Fan/ip/mblaze_Multifunction_Fan_dlmb_v10_1/sim/mblaze_Multifunction_Fan_dlmb_v10_1.vhd" \
    "$ref_dir/../../../bd/mblaze_Multifunction_Fan/ip/mblaze_Multifunction_Fan_ilmb_v10_1/sim/mblaze_Multifunction_Fan_ilmb_v10_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lmb_bram_if_cntlr_v4_0_17 $vhdlan_opts \
    "$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/db6f/hdl/lmb_bram_if_cntlr_v4_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/mblaze_Multifunction_Fan/ip/mblaze_Multifunction_Fan_dlmb_bram_if_cntlr_1/sim/mblaze_Multifunction_Fan_dlmb_bram_if_cntlr_1.vhd" \
    "$ref_dir/../../../bd/mblaze_Multifunction_Fan/ip/mblaze_Multifunction_Fan_ilmb_bram_if_cntlr_1/sim/mblaze_Multifunction_Fan_ilmb_bram_if_cntlr_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/4fba" +incdir+"$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/ec67/hdl" +incdir+"F:/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/2985/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/4fba" +incdir+"$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/ec67/hdl" +incdir+"F:/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/mblaze_Multifunction_Fan/ip/mblaze_Multifunction_Fan_lmb_bram_1/sim/mblaze_Multifunction_Fan_lmb_bram_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mdm_v3_2_17 $vhdlan_opts \
    "$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/f9aa/hdl/mdm_v3_2_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/mblaze_Multifunction_Fan/ip/mblaze_Multifunction_Fan_mdm_1_1/sim/mblaze_Multifunction_Fan_mdm_1_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/mblaze_Multifunction_Fan/ip/mblaze_Multifunction_Fan_rst_clk_wiz_0_100M_1/sim/mblaze_Multifunction_Fan_rst_clk_wiz_0_100M_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_22 $vhdlan_opts \
    "$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/f71e/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/mblaze_Multifunction_Fan/ip/mblaze_Multifunction_Fan_axi_gpio_0_2/sim/mblaze_Multifunction_Fan_axi_gpio_0_2.vhd" \
    "$ref_dir/../../../bd/mblaze_Multifunction_Fan/ip/mblaze_Multifunction_Fan_axi_gpio_0_3/sim/mblaze_Multifunction_Fan_axi_gpio_0_3.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/4fba" +incdir+"$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/ec67/hdl" +incdir+"F:/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/4fba" +incdir+"$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/ec67/hdl" +incdir+"F:/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/4fba" +incdir+"$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/ec67/hdl" +incdir+"F:/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/72d4/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/4fba" +incdir+"$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/ec67/hdl" +incdir+"F:/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/276e/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_5 $vhdlan_opts \
    "$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/276e/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/4fba" +incdir+"$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/ec67/hdl" +incdir+"F:/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/276e/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/4fba" +incdir+"$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/ec67/hdl" +incdir+"F:/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/60de/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/4fba" +incdir+"$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/ec67/hdl" +incdir+"F:/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/6b0d/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/4fba" +incdir+"$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/ec67/hdl" +incdir+"F:/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/mblaze_Multifunction_Fan/ip/mblaze_Multifunction_Fan_xbar_1/sim/mblaze_Multifunction_Fan_xbar_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_uartlite_v2_0_24 $vhdlan_opts \
    "$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/d8db/hdl/axi_uartlite_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/mblaze_Multifunction_Fan/ip/mblaze_Multifunction_Fan_axi_uartlite_0_1/sim/mblaze_Multifunction_Fan_axi_uartlite_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/4fba" +incdir+"$ref_dir/../../../../Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_Multifunction_Fan/ipshared/ec67/hdl" +incdir+"F:/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/mblaze_Multifunction_Fan/ipshared/dccb/src/Clock_Library_.v" \
    "$ref_dir/../../../bd/mblaze_Multifunction_Fan/ipshared/dccb/src/DHT11_Thermo_hum_sens.v" \
    "$ref_dir/../../../bd/mblaze_Multifunction_Fan/ipshared/dccb/src/FND_4digit_cntr.v" \
    "$ref_dir/../../../bd/mblaze_Multifunction_Fan/ipshared/dccb/src/PWM_100x.v" \
    "$ref_dir/../../../bd/mblaze_Multifunction_Fan/ipshared/dccb/src/UltraSonic.v" \
    "$ref_dir/../../../bd/mblaze_Multifunction_Fan/ipshared/dccb/src/exam01_combinational_Logic.v" \
    "$ref_dir/../../../bd/mblaze_Multifunction_Fan/ipshared/dccb/src/exam02_sequential_logic.v" \
    "$ref_dir/../../../bd/mblaze_Multifunction_Fan/ipshared/dccb/src/fan_bluetooth_top.v" \
    "$ref_dir/../../../bd/mblaze_Multifunction_Fan/ipshared/dccb/src/fan_emcy_top.v" \
    "$ref_dir/../../../bd/mblaze_Multifunction_Fan/ipshared/dccb/src/fan_led_top.v" \
    "$ref_dir/../../../bd/mblaze_Multifunction_Fan/ipshared/dccb/src/fan_speaker_top.v" \
    "$ref_dir/../../../bd/mblaze_Multifunction_Fan/ipshared/dccb/src/fan_speed_cntr_source.v" \
    "$ref_dir/../../../bd/mblaze_Multifunction_Fan/ipshared/dccb/src/fan_speed_cntr_top.v" \
    "$ref_dir/../../../bd/mblaze_Multifunction_Fan/ipshared/dccb/src/fan_temp_humid_top.v" \
    "$ref_dir/../../../bd/mblaze_Multifunction_Fan/ipshared/dccb/src/fan_timer_top.v" \
    "$ref_dir/../../../bd/mblaze_Multifunction_Fan/ipshared/dccb/src/fan_top.v" \
    "$ref_dir/../../../bd/mblaze_Multifunction_Fan/ipshared/dccb/hdl/myip_multifunction_fan_v1_0_S00_AXI.v" \
    "$ref_dir/../../../bd/mblaze_Multifunction_Fan/ipshared/dccb/hdl/myip_multifunction_fan_v1_0.v" \
    "$ref_dir/../../../bd/mblaze_Multifunction_Fan/ip/mblaze_Multifunction_Fan_myip_multifunction_f_0_2/sim/mblaze_Multifunction_Fan_myip_multifunction_f_0_2.v" \
    "$ref_dir/../../../bd/mblaze_Multifunction_Fan/sim/mblaze_Multifunction_Fan.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.mblaze_Multifunction_Fan xil_defaultlib.glbl -o mblaze_Multifunction_Fan_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./mblaze_Multifunction_Fan_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./mblaze_Multifunction_Fan.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key mblaze_Multifunction_Fan_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc mblaze_Multifunction_Fan_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./mblaze_Multifunction_Fan.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: mblaze_Multifunction_Fan.sh [-help]\n\
Usage: mblaze_Multifunction_Fan.sh [-lib_map_path]\n\
Usage: mblaze_Multifunction_Fan.sh [-reset_run]\n\
Usage: mblaze_Multifunction_Fan.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
