# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/Microblaze_hello/ip/Microblaze_hello_dlmb_bram_if_cntlr_0/Microblaze_hello_dlmb_bram_if_cntlr_0.xci
# IP: The module: 'Microblaze_hello_dlmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/Microblaze_hello/ip/Microblaze_hello_dlmb_bram_if_cntlr_0/Microblaze_hello_dlmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Microblaze_hello_dlmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: F:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/Microblaze_hello/ip/Microblaze_hello_dlmb_bram_if_cntlr_0/Microblaze_hello_dlmb_bram_if_cntlr_0.xci
# IP: The module: 'Microblaze_hello_dlmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/Microblaze_hello/ip/Microblaze_hello_dlmb_bram_if_cntlr_0/Microblaze_hello_dlmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Microblaze_hello_dlmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
