# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_led/ip/mblaze_led_axi_gpio_0_1/mblaze_led_axi_gpio_0_1.xci
# IP: The module: 'mblaze_led_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_led/ip/mblaze_led_axi_gpio_0_1/mblaze_led_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mblaze_led_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_led/ip/mblaze_led_axi_gpio_0_1/mblaze_led_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mblaze_led_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_led/ip/mblaze_led_axi_gpio_0_1/mblaze_led_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'mblaze_led_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_led/ip/mblaze_led_axi_gpio_0_1/mblaze_led_axi_gpio_0_1.xci
# IP: The module: 'mblaze_led_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_led/ip/mblaze_led_axi_gpio_0_1/mblaze_led_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mblaze_led_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_led/ip/mblaze_led_axi_gpio_0_1/mblaze_led_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mblaze_led_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_led/ip/mblaze_led_axi_gpio_0_1/mblaze_led_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'mblaze_led_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
