# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_I2C/ip/mblaze_I2C_clk_wiz_0_0/mblaze_I2C_clk_wiz_0_0.xci
# IP: The module: 'mblaze_I2C_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_I2C/ip/mblaze_I2C_clk_wiz_0_0/mblaze_I2C_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mblaze_I2C_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_I2C/ip/mblaze_I2C_clk_wiz_0_0/mblaze_I2C_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mblaze_I2C_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_I2C/ip/mblaze_I2C_clk_wiz_0_0/mblaze_I2C_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mblaze_I2C_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_I2C/ip/mblaze_I2C_clk_wiz_0_0/mblaze_I2C_clk_wiz_0_0.xci
# IP: The module: 'mblaze_I2C_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_I2C/ip/mblaze_I2C_clk_wiz_0_0/mblaze_I2C_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mblaze_I2C_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_I2C/ip/mblaze_I2C_clk_wiz_0_0/mblaze_I2C_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mblaze_I2C_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/Ian_Jung/workplace/cora_z7/cora_cpu_2019/Basys3_Microblaze_real/Basys3_Microblaze_real.srcs/sources_1/bd/mblaze_I2C/ip/mblaze_I2C_clk_wiz_0_0/mblaze_I2C_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mblaze_I2C_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
